### ISSUE TITLE
Filter config.json with environment value.

### ISSUE THREAD

**Issue by laranicolas** [ajwhite/gulp-ng-config#13]
"development": {
  "string": "my string",
  "integer": 12345,
  "object": {"one": 2, "three": ["four"]},
  "array": ["one", 2, {"three": "four"}, [5, "six"]]
},
"staging": {
  "string": "my string",
  "integer": 12345,
  "object": {"one": 2, "three": ["four"]},
  "array": ["one", 2, {"three": "four"}, [5, "six"]]
},
"production": {
  "string": "my string",
  "integer": 12345,
  "object": {"one": 2, "three": ["four"]},
  "array": ["one", 2, {"three": "four"}, [5, "six"]]
}

**Comment by ajwhite** [comment]
Are you suggesting being able to pass in a parameter that tells the gulp plugin which one of those objects to use? If so, :+1:

**Comment by laranicolas** [comment]
@ajwhite Yes of course!! I think that is easiest!

**Comment by eddie** [comment]
:+1: however, I think it would be better to switch between config files, not to store all config in one file. Perhaps this is best left to gulp and not to ng-config?

**Comment by ajwhite** [comment]
@eddie I think multiple configs would mean deciding your source for the gulp stream, yes.

However, @laranicolas's suggestion I think is also a good one -- I could see it going either way here, in which we'd handle that in `gulp-ng-config` obviously.

I think both are valid, and would like to have the flexibility of both

**Comment by ajwhite** [comment]
Added in https://github.com/ajwhite/gulp-ng-config/pull/18 and will be in the `v1.1.0` release.

Thanks for your suggestion

**Comment by laranicolas** [comment]
Cool!!! The next release suggested I will try to do it!
