### ISSUE TITLE
Needs support for reading configuration from YAML files.

### ISSUE THREAD

**Issue by vikasgarghb** [ajwhite/gulp-ng-config#19]
I see that currently it just supports config from json file, it will be better to have it support yaml file as well.

**Comment by ajwhite** [comment]
I could see yaml parsing if there's need for it..

Is this something you're currently in need of support for?

**Comment by vikasgarghb** [comment]
Having a YAML config support is good and we use YAML extensively in our projects. So, it would be good to have sooner.

**Comment by ajwhite** [comment]
Alright, I personally haven't seen much use for it other than for service providers, but I can see why applications may use it for their own configuration.

Will look into this support for an upcoming release :+1:
