### ISSUE TITLE
allow more control over output file

### ISSUE THREAD

**Issue by parliament718** [ajwhite/gulp-ng-config#34]
```

  gulp.src('config/local.json')
    .pipe(extend('config/defaults.json'))
    .pipe(ngConfig('config-module'))
    .pipe(gulp.dest("app/"));

```

I use gulp-extend because I need to extend defaults.json with local.json AND THEN pipe it into ngConfig.

However, the output file created is:

app/config/defaults.js

Whereas I need it to output 

app/config.js

Can we please get more control over the file name (it's not necessarily the same as the json file name) 
and well as not creating the extra config folder (since gulp.dest is already specified it should output there directly).

**Comment by ajwhite** [comment]
Can't you pipe [gulp-rename](https://www.npmjs.com/package/gulp-rename) before the output?

**Comment by parliament718** [comment]
Didn't know about that one. Thanks, it worked.
