### ISSUE TITLE
Not always CONSTANTS.

### ISSUE THREAD

**Issue by laranicolas** [ajwhite/gulp-ng-config#37]
Option to generate angular config file with values instead constants.

angular.module('myApp.config', [])
.value('string', "my string");

**Comment by ajwhite** [comment]
Cool, I'm thinking about adding an option `type` that can either be `value` or `constant`, and default to `constant`, :+1: ?

**Comment by laranicolas** [comment]
Awesome! Because I need to mofify config values and how they are constants, I can't!

Thanks!

**Comment by ajwhite** [comment]
Added in #46!

You can now use
```js
gulpNgConfig('name', {
  type: 'value'
})
```

This will be available in the `1.3` release :+1:

**Comment by laranicolas** [comment]
Awesome! Thanks @ajwhite
