### ISSUE TITLE
Release 1.3.0 ?

### ISSUE THREAD

**Issue by rumpl** [ajwhite/gulp-ng-config#53]
Hey, 

First, thank you for this module, it looks great!

Are you planning to release the version 1.3 ?

Thanks

**Comment by ajwhite** [comment]
Ney @rumpl - thanks for bringing this to attention. There are a few cleanup tasks that need to be done. I've put this on my schedule to get out in the next week or so.

**Comment by rumpl** [comment]
Awesome! 

If I can help I would gladly do it. I want to use your module at work. So basically I can find the time to help you out :)

**Comment by ajwhite** [comment]
Thanks :smile: 

If I need a hand, I'll open an issue with some checklist items :+1: Appreciate it!

**Comment by ajwhite** [comment]
@rumpl, regarding:

>  I want to use your module at work.

Are there any specific features that you need that aren't in the current release? In `1.3.0` we added ES6 templates - is that your current need?

**Comment by trainerbill** [comment]
@ajwhite I need the type switching functionality.  Constant to value.

**Comment by ajwhite** [comment]
Kk, going to dive into this now

**Comment by trainerbill** [comment]
@ajwhite Awesome appreciate it.

I am using
npm install ajwhite/gulp-ng-config#develop
for now and seems to work.

**Comment by ajwhite** [comment]
Oh good - I was just running through and testing this to make sure there's nothing breaking. It's helpful to hear that you've been fine on that branch. Just going to audit the recent merges and see if anything has been left out. It's been a couple months so I need to refresh 😄

**Comment by ajwhite** [comment]
`v1.3.0` is now tagged & published https://github.com/ajwhite/gulp-ng-config/releases/tag/v1.3.0 👍

**Comment by trainerbill** [comment]
@ajwhite just installed 1.3 and works for my needs.  Appreciate the quick response on this!

**Comment by rumpl** [comment]
Awesome! Thank you veru much :)
