### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by sanchobouillant** [ajwhite/gulp-ng-config#54]
Hello,

I installed gulp-ng-config with the command "npm install gulp-ng-config; bower install".

When i run "gulp test", i got:
```

ReferenceError: Can't find variable: require
  at bower_components/gulp-ng-config/gulp-ng-config.js:3
```

Any ideas ?

**Comment by ajwhite** [comment]
It looks like this is somehow being loaded as a `bower` component? Try loading this as a node module (`npm`, etc)?

**Comment by sanchobouillant** [comment]
I installed gulp-ngconfig with npm.

```
npm install gulp-ng-config --save
bower install
```

I have the same issue with `npm test`

**Comment by sanchobouillant** [comment]
I remove gulp-ng-config and i reinstall it with `npm install gulp-ng-angular`.

Everything is working fine ...
