### ISSUE TITLE
custom wrapper incorrect because of trailing colon

### ISSUE THREAD

**Issue by fariasfrancisco** [ajwhite/gulp-ng-config#73]
I have the following custom wrapper:
```javascript
wrap: '\'use strict\'\n\nimport angular from \'angular\'\n\nexport default <%= module %>\n  .name\n'
```
the expected output is:
```javascript
'use strict'

import angular from 'angular'

export default angular.module("sisaApp.config", [])
.constant("environment", "development")
  .name
```

but I get this:
```javascript
'use strict'

import angular from 'angular'

export default angular.module("sisaApp.config", [])
.constant("environment", "development");

  .name
```

the `;` screws up with my code. I don't use `;` because I follow standardjs.

**Comment by ajwhite** [comment]
Sorry that you ran into some trouble here!

Try using the [templateFilePath](https://github.com/ajwhite/gulp-ng-config#optionstemplatefilepath) and defining a custom template without the semi colon:

We'll basically take the [existing template](https://github.com/ajwhite/gulp-ng-config/blob/develop/template.html) and remove the `;`

```html
angular.module("<%= moduleName %>"<% if (createModule) { %>, []<% } %>)<% _.forEach(constants, function (constant) { %>
.<%= type %>("<%= constant.name %>", <%= constant.value %>)<% }) %>
```

**Comment by fariasfrancisco** [comment]
Thanks!!!
